blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/AliMD/alwatr/discussions
    about: Please ask and answer questions here.

  - name: Security Bug Bounty
    url: 'https://t.me/AlwatrSupport'
    about: Please report security vulnerabilities here.

  - name: Contact US
    url: 'https://t.me/AlwatrSupport'
    about: Direct contact to Alwatr support team at Telegram.
